In [1]:
from posprocessing_tools import *
import warnings
warnings.filterwarnings("ignore")

### Passos para o Pós-processamento

1. **Extrair os Dados:**
   - Requer a identificação da string, o caminho do arquivo e o nome das colunas.
  
2. **Converter as Colunas para Float:**
   - Requer o dataframe e as colunas que serão convertidas para o formato float.
  
3. **Filtrar o DataFrame:**
   - Requer o dataset e a string final para remover partes não necessárias.
  
4. **Converter Coordenadas Polares em Coordenadas Retangulares:**
   - Requer a lista de colunas em coordenadas polares e o dataframe para a conversão.
  
5. **Remover Linhas com uma String Específica (por exemplo, "="):**
   - Requer o dataframe e a string a ser filtrada para remover as linhas correspondentes.

### SP Steady State

In [2]:
file_path = 'C:/Codigos_VS/Projects/PowerApps/SP_STEADYSTATE_0.F09'  # Adjust the file path
column_names = ["SECTION", "BUS No", "BUS Type", "SECTION CURRENT Magnitude(A)", "SECTION CURRENT Angle(deg.)",
                "TOWER (SHUNT) CURRENT Magnitude(A)", "TOWER (SHUNT) CURRENT Angle(deg.)",
                "TOWER (SHUNT) POTENTIAL Magnitude(V)", "TOWER (SHUNT) POTENTIAL Angle(deg.)"]

columns2float = ["SECTION CURRENT Magnitude(A)", "SECTION CURRENT Angle(deg.)",
                        "TOWER (SHUNT) CURRENT Magnitude(A)", "TOWER (SHUNT) CURRENT Angle(deg.)",
                        "TOWER (SHUNT) POTENTIAL Magnitude(V)", "TOWER (SHUNT) POTENTIAL Angle(deg.)"]

columns2ret = ['SECTION CURRENT Magnitude(A)',     'SECTION CURRENT Angle(deg.)', 
            'TOWER (SHUNT) CURRENT Magnitude(A)',    'TOWER (SHUNT) CURRENT Angle(deg.)',
            'TOWER (SHUNT) POTENTIAL Magnitude(V)',  'TOWER (SHUNT) POTENTIAL Angle(deg.)']


string_finder = "                             TERMINAL NO.   2, Term2       "
df = extract_data_to_dataframe(file_path=file_path, column_names=column_names, string_finder=string_finder)
df_float = convert_columns_to_float(df, columns2float)
lt = filter_data_by_section(df_float, 'Terminal')
lt = convert_to_real_imag(lt, columns2ret)
lt = remove_rows_with(lt, str_garbage = '=')

Data extracted as DataFrame:

In [3]:
lt.head()

,SECTION,BUS No,BUS Type,SECTION CURRENT Real,SECTION CURRENT Imaginary,TOWER (SHUNT) CURRENT Real,TOWER (SHUNT) CURRENT Imaginary,TOWER (SHUNT) POTENTIAL Real,TOWER (SHUNT) POTENTIAL Imaginary
1,0,1,a,NaN,NaN,159.374339,42.710188,59.995372,1.039234e+02
2,0,2,b,NaN,NaN,-31.819198,31.814755,0.004000,2.792527e-07
3,0,3,c,NaN,NaN,19.417461,72.436608,-59.986117,1.039241e+02
4,0,4,sw,NaN,NaN,-0.908886,0.014421,31.667726,3.067852e+01
5,0,5,pipe,NaN,NaN,71.968578,102.343964,-13.753438,7.892564e+01

In [4]:
lt.to_csv('SP_LT_DATA.csv')

### Sp Pipe

In [5]:
file_path = 'C:/Codigos_VS/Projects/PowerApps/Sp_T02L04S0015.F09'  # Adjust the file path
column_names = ["SECTION", "BUS No", "BUS Type", "SECTION CURRENT Magnitude(A)", "SECTION CURRENT Angle(deg.)",
                "TOWER (SHUNT) CURRENT Magnitude(A)", "TOWER (SHUNT) CURRENT Angle(deg.)",
                "TOWER (SHUNT) POTENTIAL Magnitude(V)", "TOWER (SHUNT) POTENTIAL Angle(deg.)"]

columns2float = ["SECTION CURRENT Magnitude(A)", "SECTION CURRENT Angle(deg.)",
                        "TOWER (SHUNT) CURRENT Magnitude(A)", "TOWER (SHUNT) CURRENT Angle(deg.)",
                        "TOWER (SHUNT) POTENTIAL Magnitude(V)", "TOWER (SHUNT) POTENTIAL Angle(deg.)"]

columns2ret = ['SECTION CURRENT Magnitude(A)',     'SECTION CURRENT Angle(deg.)', 
            'TOWER (SHUNT) CURRENT Magnitude(A)',    'TOWER (SHUNT) CURRENT Angle(deg.)',
            'TOWER (SHUNT) POTENTIAL Magnitude(V)',  'TOWER (SHUNT) POTENTIAL Angle(deg.)']


string_finder = "                             TERMINAL NO.   2, Term2       "
pipe_df = extract_data_to_dataframe(file_path=file_path, column_names=column_names, string_finder=string_finder)
pipe_df = convert_columns_to_float(pipe_df, columns2float)
pipe_df = filtered_section_df = filter_data_by_section(pipe_df, 'Terminal')
pipe_df = remove_rows_with(pipe_df, str_garbage='=')
pipe_df = convert_to_real_imag(pipe_df, columns2ret)

Data extracted as DataFrame:

In [6]:
pipe_df.head()

,SECTION,BUS No,BUS Type,SECTION CURRENT Real,SECTION CURRENT Imaginary,TOWER (SHUNT) CURRENT Real,TOWER (SHUNT) CURRENT Imaginary,TOWER (SHUNT) POTENTIAL Real,TOWER (SHUNT) POTENTIAL Imaginary
1,0,1,a,NaN,NaN,28.307757,19.269728,14.789063,77.851751
2,0,2,b,NaN,NaN,-31.877887,32.327251,-0.400990,0.002806
3,0,3,c,NaN,NaN,19.127298,72.810545,-60.650646,103.870198
4,0,4,sw,NaN,NaN,125.453473,78.471210,23.118577,100.345284
5,0,5,pipe,NaN,NaN,-161.633287,39.285409,126.972104,77.318676

In [7]:
pipe_df.to_csv('Sp_PIPE_DATA.csv')

## MZ

### Observation Points

In [8]:
file_path = 'C:/Codigos_VS/Projects/PowerApps/MZ_T02L04S0015.F09'  # Adjust the file path
column_names = ["OBSERVATION POINT", "COORDINATES X", "COORDINATES Y", "COORDINATES Z",
                "POTENTIAL  REAL PART", "POTENTIAL  IMAGINARY PART", "MODULUS", 'ANGLE', "REFER. GPR"]

columns_to_float = column_names

string_finder = '                   EARTH POTENTIALS FOR PROFILE      1'
obs_df = extract_data_to_dataframe(file_path=file_path, column_names=column_names, string_finder=string_finder)
obs_df = convert_columns_to_float(obs_df, columns_to_float)
obs_df = remove_nan_rows(obs_df)

Data extracted as DataFrame:

In [9]:
obs_df.head()

,OBSERVATION POINT,COORDINATES X,COORDINATES Y,COORDINATES Z,POTENTIAL REAL PART,POTENTIAL IMAGINARY PART,MODULUS,ANGLE,REFER. GPR
1,1.0,-78.7,-100.0,0.542,9.606,12.94,16.12,53.41,5.80
2,2.0,-77.7,-100.0,0.542,9.619,12.99,16.16,53.48,5.82
3,3.0,-76.7,-100.0,0.542,9.634,13.03,16.21,53.53,5.83
4,4.0,-75.7,-100.0,0.542,9.650,13.08,16.25,53.57,5.85
5,5.0,-74.7,-100.0,0.542,9.667,13.12,16.30,53.62,5.87

In [10]:
obs_df.to_csv('MZ_OBS_POINTS.csv')

### Conductor Coating

In [11]:
start_string = "NO.   TOR   meter(s)  MODULUS    ANGLE    MODULUS   ANGLE    MODULUS   ANGLE"

finish_string = "SEG-   ORIGIN  *-------------------NODE POTENTIAL------------------*  EXT"
file_path = 'C:/Codigos_VS/Projects/PowerApps/MZ_T02L04S0015.F09'  # Adjust the file path

column_names = ["SEGMENT N0.", "ORIGIN COND", "SEGMENT LENGTH", "CURRENT INJECTED INTO SEGMENT MODULUS", 
"CURRENT INJECTED INTO SEGMENT ANGLE", "CURRENT FLOWING IN SEGMENT AT  ORIGIN MODULUS", 
"CURRENT FLOWING IN SEGMENT AT  ORIGIN ANGLE", "CURRENT FLOWING IN SEGMENT AT EXTREMITY MODULUS", 
"CURRENT FLOWING IN SEGMENT AT EXTREMITY ANGLE", "CURRENT FLOWING OUT FROM SEGMENT MODULUS", 
"CURRENT FLOWING OUT FROM SEGMENT ANGLE", "GROUND POTENTIAL OF SEGMENT MODULUS", 
"GROUND POTENTIAL OF SEGMENT ANGLE", "GROUND POTENTIAL OF COATING MODULUS", "GROUND POTENTIAL OF COATING ANGLE"] 

cond_df = extract_data_MZ(file_path, 15, start_string=start_string, finish_string=finish_string)
cond_df = processing_MZ_data(cond_df, column_names)

Data extracted as DataFrame:

In [12]:
cond_df.head()

,SEGMENT N0.,ORIGIN COND,SEGMENT LENGTH,CURRENT INJECTED INTO SEGMENT MODULUS,CURRENT INJECTED INTO SEGMENT ANGLE,CURRENT FLOWING IN SEGMENT AT ORIGIN MODULUS,CURRENT FLOWING IN SEGMENT AT ORIGIN ANGLE,CURRENT FLOWING IN SEGMENT AT EXTREMITY MODULUS,CURRENT FLOWING IN SEGMENT AT EXTREMITY ANGLE,CURRENT FLOWING OUT FROM SEGMENT MODULUS,CURRENT FLOWING OUT FROM SEGMENT ANGLE,GROUND POTENTIAL OF SEGMENT MODULUS,GROUND POTENTIAL OF SEGMENT ANGLE,GROUND POTENTIAL OF COATING MODULUS,GROUND POTENTIAL OF COATING ANGLE
1,1.0,1.0,30.07,0.0,0.0,5.098000e-13,-108.4,0.01199,159.3,0.011990,159.3,62.29,141.0,16.80,54.1
2,2.0,2.0,19.93,0.0,0.0,1.199000e-02,-20.7,0.01945,159.6,0.007462,160.2,58.66,139.8,17.97,54.9
3,3.0,3.0,50.00,0.0,0.0,1.945000e-02,-20.4,0.03704,160.6,0.017600,161.7,55.32,138.5,19.62,56.1
4,4.0,4.0,30.07,0.0,0.0,3.704000e-02,-19.4,0.04685,161.3,0.009822,163.7,51.53,136.8,21.58,57.1
5,5.0,5.0,19.93,0.0,0.0,4.685000e-02,-18.7,0.05304,161.7,0.006201,165.2,49.22,135.6,22.80,57.7

In [13]:
cond_df.to_csv("MZ_COND_COATING.csv")